### ISSUE TITLE
blockers -- conflicts

### ISSUE THREAD

**Issue by udeved** [cromnix/packages#3]
We would need blockers, conflicts array, if we want to be able to use arch repos at the beginning, say myself for kde.
Something similar to my eudev-systemdcompat package would be required.
Its also not as easy as thought to covert my arch install.

**Comment by cromerc** [comment]
Does this mean you want to implement a systemd shim into the distribution? If not could you elaborate a bit more since I am not sure if I understand what you need exactly.

**Comment by udeved** [comment]
o, but if you want to use certain arch packages, we may need some package that implements a systemd provides and also installs libsystemd mess. Purely depends what packages we require until built ourselves. 
I am kde user, so as long as we don't have kde in the repos, we would use arch kde pkgs. Afaik, there is no direct systemd depend in kde except for powerdevil, addressed best with elogind.

The blockers I mentioned would be nice, to convert say arch or manjaro into cromnix by just changing mirror and repos.

**Comment by cromerc** [comment]
Do you think that in elogind it would be enough to put provides=('systemd')?

**Comment by udeved** [comment]
Not sure, because some arch packages also require libsystemd.so  to actually work without throwing "can't ope shared lib..." errors.
I would rather opt for a standalone package, that gets pulled in to satisfy any systemd stuff that arch packages may rely on.

Regarding ck and elogind, we would need two different pam packages, because these require pam modules.

**Comment by udeved** [comment]
@cromerc 

Something like this? Ugly, but does the job.

https://github.com/cromnix/packages/commit/b3f18976d0c33cd10f0839dffa8e8ad99b6475b0

We don't pollute other builds with systemd stuff, and we can drop it as soon as we don't need any systemd depend arch pkg.
