### ISSUE TITLE
arch compatibility

### ISSUE THREAD

**Issue by udeved** [cromnix/packages#7]
### core libsystemd

- [x] dbus
- [x] dhcpcd
- [x] libusb
- [x] openvpn
- [x] procps-ng
- [x] rpcbind
- [x] util-linux

### extra libsystemd

- [ ] ceph
- [ ] libatasmart
- [ ] libgsystem
- [ ] libgudev
- [ ] mariadb
- [ ] php-embed
- [ ] xf86-input-evdev
- [ ] xf86-input-vmmouse
- [ ] xf86-input-wacom
- [ ] xf86-video-amdgpu
- [ ] xf86-video-ati
- [ ] xf86-video-intel
- [ ] xf86-video-nouveau
- [ ] xf86-video-openchrome
- [ ] xorg-server-xephyr
- [ ] xorg-server-xnest
- [ ] xorg-server-xvfb
- [ ] xorg-server-xwayland

### core systemd

- [x] crda
- [x] device-mapper
- [x] lvm2
- [x] mkinitcpio
- [x] pcmciautils

### extra systemd

- [ ] accountsservice
- [ ] archivetools
- [ ] bluez-hid2hci
- [ ] bluez-plugins
- [ ] bluez-utils
- [ ] chromium
- [ ] colord
- [ ] cups
- [ ] libinput
- [ ] libmbim
- [ ] libpulse
- [ ] libwacom
- [ ] lighttpd
- [ ] media-player-info
- [ ] modemmanager
- [ ] pgbouncer
- [ ] php-fpm
- [ ] pkgstats
- [ ] polkit
- [ ] rtkit
- [ ] subversion
- [ ] syslog-ng
- [ ] transmission-cli
- [ ] upower
- [ ] xdg-user-dirs
- [ ] xorg-xdm
- [ ] ypbind-mt

### community libsystemd

- [ ] docker
- [ ] hatari
- [ ] libudev0-shim
- [ ] pacredir
- [ ] parity
- [ ] powerdns-recursor
- [ ] rsyslog
- [ ] snap-confine
- [ ] usbip
- [ ] uwsgi
- [ ] weston

### community systemd

- [ ] cloud-init
- [ ] cor
- [ ] dnscrypt-proxy
- [ ] elasticsearch
- [ ] envoy
- [ ] fcgiwrap
- [ ] gnokii
- [ ] java-rxtx
- [ ] kmscon
- [ ] liblogging
- [ ] lockdev
- [ ] mailman
- [ ] matrix-synapse
- [ ] onboard
- [ ] pcsclite
- [ ] powerdns
- [ ] qopenvpn
- [ ] rkt
- [ ] spice-vdagent
- [ ] toxcore

**Comment by cromerc** [comment]
https://github.com/cromnix/packages/tree/cromer/archcompat

Something like this should help for the transition.

**Comment by udeved** [comment]
Nice.

Do we structure this tree with subfolders?

eg 

devel
|--- python builds
|--- perl builds
|--- ruby builds

etc... ? We could tale lots of the base dev languages directly from arch.
I would first do an arch minus systemd, and go from there to make it cromnix.
I have such a huge pile of packages to add just for all the makedepends doc stuff, pretty uhm, plentiful.

**Comment by cromerc** [comment]
Sub folders could help us keep it all organized. The idea would be that packages in the "archcompat" folder we would eliminate over time as we officially make our own PKGBUILDs for Cromnix. So yeah, anything to be built for arch should go into this folder.

I just opened a PR with this and a few other changes. I cannot approve my own PR, my PR has to be reviewed by another person and then that person can do the merge:
https://github.com/cromnix/packages/pull/8

**Comment by udeved** [comment]
My idea was (on manjaro), eliminate slowly all the systemd stuff.
I ended up with a plasma system, that only had depends on mariadb, NM and MM.

So, eg my openrc-base build reflects packages that are in arch base group.
We could have a openrc-main or openrc-cromnix equivalent.
In fact, tehe packages-openrc are somewhat complete set with some exceptions.

The idea is, we basically filter out from arch tree what doesn't have systemd stuff in it, and start with only these packages that replace arch packages. 
This means, any package on arch that would have a *nosystemd suffix, would be a cromnix package, but be wedesign the arch groups. ie, we start with a set of base and base-devel, assign new groups, and go from there.
We could then automate to import the arch PKGBUILDs ito archlinux git repo.
So we would rely to some extend on arch tree, which has the advantage that its maintained, and we maintainn cromnix packages git repo. Over time, we elimiate ay PKGBUILD that comes from arch.
The sheer amount of required depends atm slows us down, we should first do all dev languages and dev packages required to build. Especially gtk is hugry for depends, graphviz is a little monster.

**Comment by cromerc** [comment]
That sounds good to me.

**Comment by udeved** [comment]
My though is, we basically make all packages that have systemd stuff in it neutral, we just rip out the systemd stuff, repackage it, and the make eg openrc a layer on top of them, that could be replaced with s6 or runit.

**Comment by udeved** [comment]
Its much easier to alter builds and stuff on a running system that already has a full set of common dev packages in repos. We need that. :)

**Comment by cromerc** [comment]
I agree, the dev packages are needed to build pretty much everything else. That and various libs.

Does the PR review system that I activated work properly?

**Comment by udeved** [comment]
I guess PR works, I'll take a look at it in couple of minutes.

I made a new repo, we grow the history in packages pretty big otherwise already at start.

**Comment by udeved** [comment]
@cromerc 

We have these package depends on arch...


libsystemd...

```

==> Packages which depend on libsystemd:
core/dbus 1.10.18-1 [installed]
core/dhcpcd 6.11.5-1 (base) [installed]
core/libusb 1.0.21-2 [installed]
core/openvpn 2.4.3-1
core/procps-ng 3.3.12-1 (base) [installed]
core/rpcbind 0.2.4-3
core/systemd 232-8 [installed: 233-5]
core/util-linux 2.29.2-2 (base base-devel) [installed: 2.30-2]
extra/ceph 10.2.5-2
extra/gnome-bluetooth 3.20.1+1+ge902d1a-1
extra/gnome-settings-daemon 3.24.2-1 (gnome)
extra/libatasmart 0.19-3 [installed]
extra/libgsystem 2015.2+4+gd606bec-1
extra/libgudev 231+1+g0841288-1 [installed]
extra/mariadb 10.1.24-1 [installed]
extra/php-embed 7.1.6-1
extra/python-systemd 233-1
extra/python2-systemd 233-1
extra/xf86-input-evdev 2.10.5-1 (xorg-drivers)
extra/xf86-input-vmmouse 13.1.0-3 (xorg-drivers)
extra/xf86-input-wacom 0.34.2-1
extra/xf86-video-amdgpu 1.3.0-1 (xorg-drivers)
extra/xf86-video-ati 1:7.9.0-1 (xorg-drivers)
extra/xf86-video-intel 1:2.99.917+777+g6babcf15-1 (xorg-drivers)
extra/xf86-video-nouveau 1.0.15-1 (xorg-drivers)
extra/xf86-video-openchrome 0.6.0-1 (xorg-drivers)
extra/xorg-server-xephyr 1.19.3-2 (xorg)
extra/xorg-server-xnest 1.19.3-2 (xorg)
extra/xorg-server-xvfb 1.19.3-2 (xorg)
extra/xorg-server-xwayland 1.19.3-2 (xorg) [installed]
community/docker 1:17.05.0-1
community/hatari 2.0.0-1
community/libudev0-shim 1-2
community/pacredir 0.3.0-1
community/parity 1.6.8-3
community/powerdns-recursor 4.0.4-5
community/rsyslog 8.27.0-1
community/snap-confine 2.26.1-1
community/usbip 4.11-2 (linux-tools)
community/uwsgi 2.0.15-3
community/weston 2.0.0-2

```
systemd...

```
==> Packages which depend on systemd:
core/crda 3.18-1
core/device-mapper 2.02.171-1 (base) [installed]
core/lvm2 2.02.171-1 (base) [installed]
core/mkinitcpio 23-1 [installed]
core/netctl 1.12-2 (base) [installed: 1.13-2]
core/pcmciautils 018-7 (base) [installed]
core/systemd-sysvcompat 232-8 (base) [installed: 233-5]
extra/accountsservice 0.6.45-1 [installed]
extra/archboot 2016.08-1
extra/archivetools 2-1
extra/bluez-hid2hci 5.45-1
extra/bluez-plugins 5.45-1
extra/bluez-utils 5.45-1
extra/chromium 59.0.3071.109-1
extra/colord 1.3.5-1 [installed]
extra/cups 2.2.3-1
extra/flatpak 0.9.6-1
extra/gnome-logs 3.24.1+1+gf949685-1 (gnome-extra)
extra/gnome-session 3.24.1-1 (gnome)
extra/gnome-session 3.24.1-1 (gnome)
extra/gnome-system-monitor 3.24.0+4+g9140c85a-1 (gnome)
extra/libgdm 3.24.2-1
extra/libinput 1.7.3-1 [installed]
extra/libmbim 1.14.0-4 [installed]
extra/libpulse 10.0-3 [installed]
extra/libwacom 0.24-1 [installed]
extra/lighttpd 1.4.45-2
extra/media-player-info 22-2 [installed]
extra/modemmanager 1.6.8-1 [installed]
extra/pgbouncer 1.7.2-2
extra/php-fpm 7.1.6-1
extra/pkgstats 2.3-7
extra/polkit 0.113+29+g3272a98-1 [installed]
extra/rtkit 0.11+6+g417bb7d-1 [installed]
extra/subversion 1.9.5-3
extra/syslog-ng 3.9.1-6
extra/transmission-cli 2.92-6
extra/upower 0.99.4+12+g402640b-1 [installed]
extra/xdg-user-dirs 0.15-4
extra/xorg-xdm 1.1.11-6
extra/ypbind-mt 1.38-1
community/cloud-init 0.7.9-1
community/cor 0.1.17-2
community/dnscrypt-proxy 1.9.4-1
community/elasticsearch 5.4.2-1
community/envoy 14-2
community/fcgiwrap 1.1.0-4
community/gnokii 0.6.31-12
community/java-rxtx 2.2pre2-4
community/kmscon 8-3
community/liblogging 1.0.6-1
community/lockdev 1.0.3_1.6-4
community/mailman 2.1.24-1
community/matrix-synapse 0.21.1-1
community/onboard 1.4.1-2
community/pcsclite 1.8.22-1
community/powerdns 4.0.3-5
community/qopenvpn 2.0.0-1
community/rkt 1.27.0-1
community/spice-vdagent 0.17.0-3
community/systemd-swap 3.3.0-1
community/toxcore 1:0.1.9-3
```

Additionally, there are many packages that provide unit files, that may not have a direct systemd depend.

**Comment by cromerc** [comment]
Are you running this from a pure systemd arch linux? Or from arch-openrc? Because in arch-openrc the nosystemd has packages that clean up some of those. For example there is mkinitcpio-nosystemd.

**Comment by udeved** [comment]
Pure arch systemd.
I can use my manjaro install for nosystemd/openrc reference in terms of eliminated depends. :)

We got 98 packages we need to do ourselves for the start, which is doable.

```
dbus
dhcpcd
libusb
openvpn
procps-ng
rpcbind
util-linux
ceph
gnome-bluetooth
gnome-settings-daemon
libatasmart
libgsystem
libgudev
mariadb
php-embed
xf86-input-evdev
xf86-input-vmmouse
xf86-input-wacom
xf86-video-amdgpu
xf86-video-ati
xf86-video-intel
xf86-video-nouveau
xf86-video-openchrome
xorg-server-xephyr
xorg-server-xnest
xorg-server-xvfb
xorg-server-xwayland
docker
hatari
libudev0-shim
pacredir
parity
powerdns-recursor
rsyslog
snap-confine
usbip
uwsgi
weston
crda
device-mapper
lvm2
mkinitcpio
netctl
pcmciautils
accountsservice
archboot
archivetools
bluez-hid2hci
bluez-plugins
bluez-utils
chromium
colord
cups
flatpak
gnome-logs
gnome-session
gnome-session
gnome-system-monitor
libgdm
libinput
libmbim
libpulse
libwacom
lighttpd
media-player-info
modemmanager
pgbouncer
php-fpm
pkgstats
polkit
rtkit
subversion
syslog-ng
transmission-cli
upower
xdg-user-dirs
xorg-xdm
ypbind-mt
cloud-init
cor
dnscrypt-proxy
elasticsearch
envoy
fcgiwrap
gnokii
java-rxtx
kmscon
liblogging
lockdev
mailman
matrix-synapse
onboard
pcsclite
powerdns
qopenvpn
rkt
spice-vdagent
toxcore
```

**Comment by udeved** [comment]
Some stats.

libsystemd depend pkgs
core: 6 
extra: 19 
community: 11

systemd depend pkgs
core: 5
extra: 33 
community: 19

**Comment by cromerc** [comment]
Those stats right there are the reason I don't like systemd. It hooks into everything everywhere. And those don't include packages that build against sysemd without saying that they do.

**Comment by udeved** [comment]
Yes, but we would replace these packages with our own, init neutral.

Currently writing a little script that imports these builds in the packages-cromnix repo.
All the rest of arch builds would go in archliux repo.
So the idea, that annother script can later basically remote track and sync arch tree minus our packages. We use the list with scripts.

**Comment by cromerc** [comment]
That would be perfect, plus with the buildbot it could all be automated.

**Comment by udeved** [comment]
Right, by time, we simply ed up with more and more PKGBUILDs in packages-cromnix, and less and less PKGBUILDs in archlinux.

Whatever package we encounter that installs systemd units will be slowly added to our list.

**Comment by udeved** [comment]
You can still do stuff in packages repo, and simply later transfer your work.

**Comment by udeved** [comment]
@cromerc 

https://github.com/cromnix/packages-cromnix/tree/devel

We could do similar for archlinux repo.

**Comment by cromerc** [comment]
Looks good.

We need to add a blacklist to the script because some of those packages already exist under cromnix.

**Comment by udeved** [comment]
Yeah, can do that later.
Currently doing the same for archliux, it excludes the ones in packages-cromnix.
I plan to replace cp with rsync in the scripts.

Initial import of archlinux minus filer is roughly 2500 builds from packages, no communnity imports.

**Comment by udeved** [comment]
The plan would be, to only have our overlay packages, and add cromix repos in arch pacman.conf above the arch repos, to we can build packages in chroot.

**Comment by udeved** [comment]
I have come up with good rsync of arch now.
We'd just maintain lists with builds, or stuff we want to block.
It will simply sync everything thats newer from arch as defied in lists.

https://github.com/cromnix/packages-cromnix/blob/core/import_arch.sh

It can be integrated in artools later on.

**Comment by udeved** [comment]
I have created a complete set of arch's core repo but with no systemd.

https://github.com/cromnix/packages-cromnix/tree/core
